### PR TITLE
Expand Responder event error testing

### LINKED ISSUE #3267: `UnsupportedError` response to `SEND_EVENT` uses incorrect `RequestResponseCode`
https://github.com/DMTF/libspdm/blob/09f1ac3dc1e5935363ea62a91fb91e4f491e2e5d/library/spdm_responder_lib/libspdm_rsp_event_ack.c#L37-L41

`SPDM_KEY_UPDATE` -> `SPDM_SEND_EVENT`

### PR DESCRIPTION
**Pull request by steven-bellock**
This also fixes #3267, which was discovered in the course of adding these test cases.

These test cases were guided by the following coverage reports:
- https://dmtf.github.io/libspdm/coverage_log/library/spdm_responder_lib/libspdm_rsp_event_ack.c.gcov.html
- https://dmtf.github.io/libspdm/coverage_log/library/spdm_responder_lib/libspdm_rsp_subscribe_event_types_ack.c.gcov.html
- https://dmtf.github.io/libspdm/coverage_log/library/spdm_responder_lib/libspdm_rsp_supported_event_types.c.gcov.html

### CODE REVIEW

File: unit_test/test_spdm_responder/error_test/event_ack_err.c [hunk 1]
```diff
@@ -350,15 +355,240 @@ static void rsp_event_ack_err_case4(void **state)
...
+    generate_dmtf_event_data(send_event + 1, &event_data_size, 0x11223344,
+                             SPDM_DMTF_EVENT_TYPE_EVENT_LOST, &event_lost);
+
+    m_event_counter = 0;
+    m_expected_event[0].event_instance_id = 0x11223344;
+    m_expected_event[0].svh_id = SPDM_REGISTRY_ID_DMTF;
+    m_expected_event[0].svh_vendor_id_len = 0;
+    m_expected_event[0].event_type_id = SPDM_DMTF_EVENT_TYPE_EVENT_LOST;
+    m_expected_event[0].event_detail_len = SPDM_DMTF_EVENT_TYPE_EVENT_LOST_SIZE;
+    memcpy(m_expected_event[0].event_detail, &event_lost, SPDM_DMTF_EVENT_TYPE_EVENT_LOST_SIZE);
```
Comment (steven-bellock) [inline unit_test/test_spdm_responder/error_test/event_ack_err.c]: This is not needed as they are not checked.
