### PR TITLE
Fix undefined behavior in GET_MEASUREMENTS unit test

### LINKED ISSUE #1467: GET_MEASUREMENTS unit test fails with new version of CLANG
See https://github.com/DMTF/libspdm/actions/runs/3606157422/jobs/6077233741
When running it through Valgrind it produces
```
==19118== Invalid read of size 1
==19118==    at 0x4AEC69: libspdm_transport_test_decode_message (in /home/sbellock/repo/steven-bellock/libspdm/build/bin/test_spdm_requester)
==19118==    by 0x4A3052: libspdm_receive_spdm_response (in /home/sbellock/repo/steven-bellock/libspdm/build/bin/test_spdm_requester)
==19118==  Address 0x1ffeffce70 is on thread 1's stack
==19118==  4544 bytes below stack pointer
==19118==
[  ERROR   ] --- 0x80010002 != 0
[   LINE   ] --- /home/sbellock/repo/steven-bellock/libspdm/unit_test/test_spdm_requester/get_measurements.c:5415: error: Failure!
[  PASSED  ] 36 test(s).
[  FAILED  ] spdm_requester_get_measurements_tests: 1 test(s), listed below:
[  FAILED  ] libspdm_test_requester_get_measurements_case35
```

### PR DESCRIPTION
**Pull request by steven-bellock**
and re-enable CLANG in CI/CD. The `temp_buf` array was being modified at an out-of-bounds index. GCC and Visual Studio didn't mind but CLANG 14, with -O1 or higher optimizations, did. 

Note that Valgrind is picking up additional issues in `test_spdm_requester`. I'll file a separate issue for those.

Fixes #1467.

Signed-off-by: Steven Bellock <sbellock@nvidia.com>

### CODE REVIEW

File: unit_test/test_spdm_requester/get_measurements.c [hunk 1]
```diff
@@ -5415,12 +5402,13 @@ static void libspdm_test_requester_get_measurements_case35(void **state)
     assert_int_equal(status, LIBSPDM_STATUS_SUCCESS);
 
 #if LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT
-    assert_int_equal(spdm_context->transcript.message_m.buffer_size,
+    /* Subtract the size of the request message. */
```
Comment (jyao1) [inline unit_test/test_spdm_requester/get_measurements.c:5405]: Why we need subtract the request message?

Comment (steven-bellock) [reply unit_test/test_spdm_requester/get_measurements.c]: I changed it so that the buffers contains everything (fill data, request, and response), and the expectation is that the sizes of the two buffers are the same as well as the contents.
