### PR TITLE
Handle "error" if no encapsulated request

### LINKED ISSUE #3031: Requester does not handle "encapsulated" errors from Responder
As detailed in https://github.com/DMTF/SPDM-WG/issues/3992, if the Requester issues `GET_ENCAPSULATED_REQUEST` and the Responder does not have any encapsulated requests, the Responder can reply with `UnexpectedRequest` or `NoPendingRequests`. However the libspdm Requester does not accommodate this, and expects only an `ENCAPSULATED_REQUEST` from the Responder.

### PR DESCRIPTION
**Pull request by steven-bellock**
Fix #3031.

### CODE REVIEW

File: library/spdm_requester_lib/libspdm_req_encap_request.c [hunk 1]
```diff
@@ -235,13 +235,39 @@ libspdm_return_t libspdm_encapsulated_request(libspdm_context_t *spdm_context,
...
+            const uint8_t error_code = libspdm_encapsulated_request_response->header.param1;
+
+            libspdm_release_receiver_buffer(spdm_context);
+
+            if (spdm_response_size < sizeof(spdm_error_response_t)) {
+                libspdm_release_receiver_buffer (spdm_context);
+                return LIBSPDM_STATUS_INVALID_MSG_SIZE;
+            }
+
+            if (mut_auth_requested == 0) {
```
Comment (jyao1) [inline library/spdm_requester_lib/libspdm_req_encap_request.c:253]: Is that enough?

Should we also consider basic_mut_auth here?

Comment (steven-bellock) [reply library/spdm_requester_lib/libspdm_req_encap_request.c:253]: `mut_auth_requested == 0` is also used for the basic mutual authentication flow. In particular only digests, certificates, and challenge should be allowed in the basic mutual authentication flow, but it does not look like libspdm explicitly enforces that. I will file a separate issue for that.

**Comment by steven-bellock** [comment]
https://github.com/DMTF/libspdm/issues/3058 should be resolved after this is merged to handle the basic mutual authentication cases.

**Review by jyao1 — APPROVED** [review]
