### PR TITLE
Validate `CHUNK_RESPONSE` handle correlation in requester

### LINKED ISSUE #3598: CHUNK_GET/CHUNK_RESPONSE Missing Explicit Requester Handle Correlation Check (param2)
Description:
Requester sends CHUNK_GET with a chunk handle in header.param2, but CHUNK_RESPONSE validation does not explicitly verify that response.param2 matches the requested handle in the large-response path.

Observed Behavior

Requester sets handle in CHUNK_GET param2.
CHUNK_RESPONSE validation covers version/code/size/sequence constraints.
No explicit response handle equality check against request handle.
Expected Behavior
Requester should reject CHUNK_RESPONSE when response.param2 differs from the requested handle, returning invalid message field.

Impact

Correlation/robustness validation gap in chunked transport flow.
Potential acceptance of mismatched chunk-response context.
Severity
Medium (protocol robustness issue, non-security by itself).

Suggested Fix
Add explicit param2 handle match check in CHUNK_GET response-validation path and add UT injecting mismatched handle.

Present in Release 3.8.2
Yes, same gap is visible in equivalent requester chunk-error handling flow.

### PR DESCRIPTION
**Pull request by czwolak**
Fix #3598.

### CODE REVIEW

File: unit_test/test_spdm_requester/chunk_get.c [hunk 1]
```diff
@@ -1170,6 +1181,80 @@ static void req_chunk_get_case8(void** state)
...
+        (uint8_t) (0xFF));
+    libspdm_reset_message_b(spdm_context);
+
+    libspdm_zero_mem(total_digest_buffer, sizeof(total_digest_buffer));
+    status = libspdm_get_digest(spdm_context, NULL, &slot_mask, &total_digest_buffer);
+    assert_int_equal(status, LIBSPDM_STATUS_INVALID_MSG_FIELD);
+}
+#endif
+
+#if LIBSPDM_SEND_GET_CERTIFICATE_SUPPORT
```
Comment (steven-bellock) [inline unit_test/test_spdm_requester/chunk_get.c]: Can still use the `#if` from line `1184`.

**Review by jyao1 — APPROVED** [review]

File: unit_test/test_spdm_requester/chunk_get.c (hunk 1 above)
Comment (czwolak) [reply unit_test/test_spdm_requester/chunk_get.c]: Thank you, removed redundant lines.

**Review by steven-bellock — APPROVED** [review]
