### PR TITLE
Fix : vendor_response_get_id should not exist

### LINKED ISSUE #3045: `vendor_response_get_id` should not exist
`libspdm_get_vendor_defined_response` makes separate calls to https://github.com/DMTF/libspdm/blob/707af3b726707ef3052922355324a04bc92c2a85/library/spdm_responder_lib/libspdm_rsp_vendor_response.c#L180-L184 and https://github.com/DMTF/libspdm/blob/707af3b726707ef3052922355324a04bc92c2a85/library/spdm_responder_lib/libspdm_rsp_vendor_response.c#L191-L197 In the case where a Responder supports multiple VDM types, for the call to `vendor_response_get_id` the Integrator is completely blind as to what data to return, as it needs to examine the request message. Only `vendor_response_callback` is needed and this should include the response VDM's `RegisteryId`, etc.

### PR DESCRIPTION
**Pull request by ShitalJumbad**
fix #3045

### CODE REVIEW

File: include/library/spdm_common_lib.h [hunk 1]
```diff
@@ -935,37 +935,25 @@ bool libspdm_get_fips_mode(void);
...
-typedef libspdm_return_t (*libspdm_vendor_get_id_callback_func)(
-    void *spdm_context,
-    const uint32_t *session_id,
-    uint16_t *resp_standard_id,
-    uint8_t *resp_vendor_id_len,
-    void *resp_vendor_id);
-
-/**
- * Vendor Response Callback Function Pointer.
+ * The library may invoke this callback twice:
```
Comment (steven-bellock) [inline include/library/spdm_common_lib.h]: No, it only needs to be called once.

**Review by steven-bellock — CHANGES_REQUESTED** [review]

File: include/library/spdm_common_lib.h [hunk 2]
```diff
@@ -946,37 +946,25 @@ bool libspdm_get_fips_mode(void);
...
-typedef libspdm_return_t (*libspdm_vendor_get_id_callback_func)(
-    void *spdm_context,
-    const uint32_t *session_id,
-    uint16_t *resp_standard_id,
-    uint8_t *resp_vendor_id_len,
-    void *resp_vendor_id);
-
-/**
- * Vendor Response Callback Function Pointer.
+ * The library invokes this callback once. The integrator should:
```
Comment (steven-bellock) [inline include/library/spdm_common_lib.h]: >The library invokes this callback once.

Can just delete this.

File: library/spdm_responder_lib/libspdm_rsp_vendor_response.c [hunk 3]
```diff
@@ -11,15 +11,6 @@
 /* expected number of bytes for VENDOR MESSAGE HEADERS */
 #define SPDM_VENDOR_DEFINED_FIXED_HEADER_LEN 7
```
Comment (steven-bellock) [inline library/spdm_responder_lib/libspdm_rsp_vendor_response.c]: Pre-existing issue, but I do not see a reason for this `#define` to exist. I will file a separate issue for it.

File: library/spdm_responder_lib/libspdm_rsp_vendor_response.c [hunk 4]
```diff
@@ -182,8 +172,8 @@ libspdm_return_t libspdm_get_vendor_defined_response(libspdm_context_t *spdm_con
     libspdm_reset_message_buffer_via_request_code(spdm_context, NULL,
                                                   spdm_request->header.request_response_code);
 
-    /* length of spdm request/response header before payload start */
-    header_length = sizeof(spdm_vendor_defined_response_msg_t) + spdm_request->len +
+    /* reserve max vendor ID in header */
+    header_length = sizeof(spdm_vendor_defined_response_msg_t) + SPDM_MAX_VENDOR_ID_LENGTH +
```
Comment (steven-bellock) [inline library/spdm_responder_lib/libspdm_rsp_vendor_response.c]: @ShitalJumbad We (mostly me) have been a little lazy in defining `SPDM_MAX_VENDOR_ID_LENGTH` as `255` bytes. Let me file an issue, resolve it with a pull request, and then you can rebase with the new value. This should simplify things so that you do not need to
>compact payload after Vendor ID

Comment (steven-bellock) [reply library/spdm_responder_lib/libspdm_rsp_vendor_response.c]: https://github.com/DMTF/SPDM-WG/issues/4396 has complicated things. Let me resolve that first.

Comment (steven-bellock) [reply library/spdm_responder_lib/libspdm_rsp_vendor_response.c]: After discussing this in the SPDM Working Group, for IANA CBOR the `VendorId` field is the CBOR-encoded tag number. As such its maximum size is nine bytes: `0xdb` plus eight bytes for the tag number. I will update `SPDM_MAX_VENDOR_ID_LENGTH` to this more precise value.

File: include/library/spdm_common_lib.h [hunk 5]
```diff
@@ -985,6 +973,9 @@ typedef libspdm_return_t (*libspdm_vendor_response_callback_func)(
     const void *req_vendor_id,
     uint32_t req_size,
     const void *req_data,
+    uint16_t *resp_standard_id,
+    uint8_t *resp_vendor_id_len,
+    void *resp_vendor_id,
```
Comment (steven-bellock) [inline include/library/spdm_common_lib.h]: @ShitalJumbad as discussed in the meeting today, please remove these parameters and have libspdm just copy the standard ID and vendor ID from the request to the response in `libspdm_rsp_vendor_response.c`.

File: include/library/spdm_common_lib.h (hunk 2 above)
Comment (ShitalJumbad) [reply include/library/spdm_common_lib.h]: Done.

File: include/library/spdm_common_lib.h (hunk 5 above)
Comment (ShitalJumbad) [reply include/library/spdm_common_lib.h]: Done.

File: library/spdm_responder_lib/libspdm_rsp_vendor_response.c (hunk 3 above)
Comment (steven-bellock) [reply library/spdm_responder_lib/libspdm_rsp_vendor_response.c]: Filed https://github.com/DMTF/libspdm/issues/3403.

File: include/library/spdm_common_lib.h [hunk 6]
```diff
@@ -977,7 +959,7 @@ typedef libspdm_return_t (*libspdm_vendor_get_id_callback_func)(
  * @param  resp_size          Length of the response
  * @param  resp_data          The vendor defined response
  **/
-typedef libspdm_return_t (*libspdm_vendor_response_callback_func)(
+ typedef libspdm_return_t (*libspdm_vendor_response_callback_func)(
```
Comment (jyao1) [inline include/library/spdm_common_lib.h]: why change this ? typo?

Comment (ShitalJumbad) [reply include/library/spdm_common_lib.h]: Correct, thanks for catching this. Updated.

**Review by steven-bellock — APPROVED** [review]
