### PR TITLE
Fix Coverity issues

### LINKED ISSUE #3333: Coverity 467430 - resource leak
`fp_in` needs to be closed before returning in line 110.

https://github.com/DMTF/libspdm/blob/8ccc0f3214c36faccb7c03b9169dfd692eee744d/unit_test/spdm_unit_test_common/support.c#L99-L110

### LINKED ISSUE #3334: Coverity 469466 - resource leak
`cached_key_pair_info` needs to be freed before returning on line 474.

https://github.com/DMTF/libspdm/blob/8ccc0f3214c36faccb7c03b9169dfd692eee744d/os_stub/spdm_device_secret_lib_sample/key_pair.c#L439-L475

### LINKED ISSUE #3335: Coverity 479595 - uninitialized scalar variable
Coverity complains that `event_detail_len` might be uninitialized. This is a false positive, but it can be remedied by adding a `default` case with failing assertion.

https://github.com/DMTF/libspdm/blob/8ccc0f3214c36faccb7c03b9169dfd692eee744d/unit_test/spdm_unit_test_common/event_support.c#L126-L141

### PR DESCRIPTION
**Pull request by steven-bellock**
Fix #3333.
Fix #3334.
Fix #3335.

### CODE REVIEW

File: unit_test/spdm_unit_test_common/event_support.c [hunk 1]
```diff
@@ -136,6 +136,8 @@ void generate_dmtf_event_data(void *buffer, uint8_t *total_bytes, uint32_t event
     case SPDM_DMTF_EVENT_TYPE_CERTIFICATE_CHANGED:
         event_detail_len = SPDM_DMTF_EVENT_TYPE_CERTIFICATE_CHANGED_SIZE;
         break;
+    default:
+        assert(false);
```
Comment (steven-bellock) [inline unit_test/spdm_unit_test_common/event_support.c:141]: I guess I can also set `event_detail_len` to `0` here too.

**Review by jyao1 — APPROVED** [review]
